[package]
name = "mithrilengine"
version = "0.0.2"
authors = ["daigennki <daigennki@users.noreply.github.com>"]
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 1   # needed to stop stack overflow in Windows debug build; see https://github.com/vulkano-rs/vulkano/issues/1790#issuecomment-1023222638

[build-dependencies]
embed-resource = "1.6.5"

[dependencies]
winit = "0.25.0"
rusttype = "0.9.2"
lodepng = "3.4.7"
vulkano = "0.27.1"
vulkano-win = "0.27.1"
# physx = "0.12.1"
# ffmpeg-next = { version = "4.4.0", features = ["codec", "format"] }
# steamworks = "0.7.0"
glm = "0.2.3"
yaml-rust = "0.4.5"
openal = "0.2.2"
mlua = { version = "0.7.1", features = ["luajit", "vendored"] }     # Configured for standalone mode for improved safety
msgbox = "0.6.0"
chrono = "0.4.19"