[package]
name = "mithrilengine"
version = "0.0.2"
authors = ["daigennki <daigennki@users.noreply.github.com>"]
edition = "2021"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
embed-resource = "1.6.5"

[dependencies]
sdl2 = { version = "0.35.1" }
# stb = "0.3.2"
vulkano = "0.27.1"
# physx = "0.12.1"
# ffmpeg-next = "4.4.0"     # broken right now, fails to build
# steamworks = "0.7.0"
glm = "0.2.3"
yaml-rust = "0.4.5"
openal = "0.2.2"
mlua = { version = "0.7.1", features = ["luajit", "vendored"] }     # "vendored" required here for Windows
msgbox = "0.6.0"
chrono = "0.4.19"