[package]
name = "mithrilengine"
version = "0.1.0"
authors = ["daigennki <daigennki@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.3"
stb = "0.3.2"
vulkano = "0.22.0"
physx = "0.11.0"
ffmpeg-next = "4.3.8"
# steamworks = "0.7.0"
glm = "0.2.3"
yaml-rust = "0.4.5"
openal = "0.2.2"
mlua = { version = "0.5.3", features = ["luajit", "vendored"] }     # "vendored" required here for Windows
msgbox = "0.6.0"
chrono = "0.4.19"